### ISSUE TITLE
Piwik tracker was not initialized before the piwik.js file was loaded

### ISSUE THREAD

**Issue by nfoenki** [awronka/Angular2Piwik#3]
When i initialize Piwik via Root Component
I got this error :
_paq.push() was used but Piwik tracker was not initialized before the piwik.js file was loaded

it works when i use the other method (Adding Piwik into myapplication via Script Tag.)

**Comment by awronka** [comment]
Was this a warning or an error? Piwik can work with actions pushed into the _paq before initialization.

**Comment by nfoenki** [comment]
it was an error
[my-test-app.zip](https://github.com/awronka/Angular2Piwik/files/1299077/my-test-app.zip)

here is my sample code from a new angular cli generated project
- it works when  i initialize Piwik via Script Tag
- it does not work when i initialize Piwik via Root Component

did i do something wrong ?

**Comment by awronka** [comment]
Your code looks fine, can we see the error? 

If you're stuck just use the script tag as it doesn't matter

**Comment by nfoenki** [comment]
If you test my app, you can see a warning in the console : "**_Piwik not found_**"
calling when use configure.piwik.tracker and use.piwik.tracker

Then when you click on the "Action" button you can see an error in the console : 
_**_paq.push() was used but Piwik tracker was not initialized before the piwik.js file was loaded. Make sure to configure the tracker via _paq.push before loading piwik.js. Alternatively, you can create a tracker via Piwik.addTracker() manually and then use _paq.push but it may not fully work as tracker methods may not be executed in the correct order.**_

I'm stuck because I need the site ID to be dynamic
Only possible with the root component initializing : 
`this.initializePiwik.init(APP_CONSTANTS.ANALYTICS.URL, APP_CONSTANTS.ANALYTICS.SITEID)`

in an Angular build, index.html file is static 
so i can't change the site id with the inclusion of piwik script in index.html. I need to change it to deploy for many platforms. each giving stats for a specific site id.

**Comment by nfoenki** [comment]
If you have any sample project that includes piwik initializing via Root Component could you put it on Plunker or Codepen ? as i never succeed to make it works

**Comment by nfoenki** [comment]
We finally found what was wrong.
In your **initialize.piwik.ts** file : 
_paq is locally declared, that's the issue.

you should use **window['_paq']** instead of **_paq**
you should use **window['_paq'].push** instead of **_paq.push** 

It works great with that change.
Can you confirm ?
Maybe you could update your code

**Comment by YiannisH** [comment]
I confirm that i have the same issue. I am using Angular 4 and the Angular2Piwik NPM package.

I can make piwik work by adding the script tag after my root component in the index.html file BUT i get the same error as @nfoenki when i try to use the instructions as those are described in https://www.npmjs.com/package/angular2piwik .

Is this indeed a bug or a misconfiguration?

**Comment by nfoenki** [comment]
i think this is a bug since _paq variable must be globally declared. And it is not the case in initialize.piwik.ts file of the angular2piwik module.

to correct it, @awronka  you may replace window['_paq'] instead of _paq in initialize.piwik.ts

**Comment by awronka** [comment]
@nfoenki Can you make the correction and I'll merge the pull request

**Comment by nfoenki** [comment]
@awronka thanks for the merge ! can you update npm package version ?

**Comment by awronka** [comment]
done

**Comment by nfoenki** [comment]
great !  thanks
